#!/bin/sh
set -e

ENV_FILE="/usr/share/nginx/html/env-config.js"

echo "Generating runtime environment configuration at ${ENV_FILE}..."

cat <<EOF > "${ENV_FILE}"
window.__ENV__ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL}",
  VITE_FIREBASE_API_KEY: "${VITE_FIREBASE_API_KEY}",
  VITE_FIREBASE_AUTH_DOMAIN: "${VITE_FIREBASE_AUTH_DOMAIN}",
  VITE_FIREBASE_PROJECT_ID: "${VITE_FIREBASE_PROJECT_ID}",
  VITE_FIREBASE_STORAGE_BUCKET: "${VITE_FIREBASE_STORAGE_BUCKET}",
  VITE_FIREBASE_MESSAGING_SENDER_ID: "${VITE_FIREBASE_MESSAGING_SENDER_ID}",
  VITE_FIREBASE_APP_ID: "${VITE_FIREBASE_APP_ID}",
  VITE_FIREBASE_MEASUREMENT_ID: "${VITE_FIREBASE_MEASUREMENT_ID}",
  VITE_SENTRY_DSN: "${VITE_SENTRY_DSN:-${SENTRY_DSN}}"
};
EOF

echo "Runtime environment configuration generated successfully."
